# 【課題1】内積を手計算しよう

$$
% <![CDATA[
A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 \\
      7 & 8 & -9
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
      0 & 2 & 1 \\
      0 & 2 & -8 \\
      2 & 9 & -1
    \end{array}
  \right] %]]>
  $$

$$
AB =\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48 
    \end{bmatrix}$$

# 【課題2】1次元配列の内積をfor文で計算しよう

In [5]:
import numpy as np
A = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
B = np.array([[0,2,1],[0,2,-8],[2,9,-1]])

In [40]:
# ０行目１列目の要素を作成
zeroiti = 0
# 0行1列をそれぞれ固定して、要素をかけたものを増やしていく
for i in range(3):
    zeroiti += (A[0,i]*B[i,1])
zeroiti

29

# 【課題3】多次元配列の内積をfor文で計算しよう

In [45]:
# 3×3の全て０行列を作成
AB = np.zeros((3,3))
# kでインデックス移動、jは列の移動、iは行の移動
for i in range(3):
    for j in range(3):
        for k in range(3):
            AB[i,j]+= A[i,k]*B[k,j]
AB

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# 【課題4】内積をnp.dotで計算しよう

In [46]:
dotAB = np.dot(A,B)
dotAB

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【課題5】内積ができないときはどうするか

- エラーの理由はAの列数とBの行数が一致していないから。
- 内積はAの行とBの列を掛け合わせたものとなるので、それぞれの要素の数が一致していないと掛け算ができない。
- $[m \times n][n \times p]$としてnの数が一致する必要がある。
- 結果は$[m \times p]$となり m行p列の成分はm行とp列の積となる。

In [48]:
A = np.array([[-1,2,3],[4,-5,6]])
B = np.array([[-9,8,7],[6,-5,4]])
# どちらかの行列を転置すればnの数が一致する。
np.dot(A,B.T)

array([[ 46,  -4],
       [-34,  73]])