# 【問題1】これまで利用してきたクラスの列挙

pandasから
- DataFrame()
- Series()

matplotlibから
- Axes
- Figure
- Subplot

sklearnから
- LogisticRegression
- SVC
- DecisionTreeClassifier
- RandomForestClassifier

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

メソッドを列挙
- DataFrame.query
- DataFrame.corr
- LogisticRegression.score
- LogisticRegression.predict
- SVC.fit

インスタンス変数を列挙
- DataFrame.columns
- DataFrame.dtypes
- DataFrame.values
- LogisticRegression.coef_
- LogisticRegression.intercept_

# 【問題3】標準化クラスをスクラッチで作成

雛形を元に標準化クラスを作成

class ScratchStandardScaler():

    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ =
        self.var_ =

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        pass
        return X_scaled

**このコードが実行出来るようにする**

import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 :", scratch_scaler.mean_)
print("分散 :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)

順を追って作成していく

In [18]:
#ランダムに１００行3列のndarrayを作成
import numpy as np
sample = np.random.rand(100,3)
sample.shape

(100, 3)

In [25]:
#平均と分散を計算（これが、mean_,var_となる予定）
mean_ = np.mean(sample,axis=0)
var_ = np.var(sample,axis=0)
std_= np.std(sample,axis=0)

In [32]:
#標準化する
sample_std = (sample-mean_)/std_
np.mean(sample_std,axis=0),np.std(sample_std,axis=0)

(array([ 7.88258347e-16,  1.25455202e-16, -4.87943019e-16]),
 array([1., 1., 1.]))

先程の流れに従って作成

In [46]:
class ScratchStandardScaler():

    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ =np.mean(X,axis=0)
        self.var_ =np.var(X,axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X-self.mean_)/self.var_**(1/2)
        
        return X_scaled

指定されたコードの実行

In [47]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 :", scratch_scaler.mean_)
print("分散 :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


In [48]:
#確認
np.mean(X_std,axis=0),np.std(X_std,axis=0)

(array([ 2.23709939e-15,  1.36557432e-15,  0.00000000e+00, -2.88657986e-16]),
 array([1., 1., 1., 1.]))

できた。

### 特殊メソッド理解のため、サンプルコードを確認

In [2]:
#サンプルコード
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

In [7]:
example = ExampleClass(5)

print("value :", example.value)

example.add(3)
print("value :", example.value)

初期値5が設定されました
value : 5
value : 8


### インスタンス化する際に--init--が実行されて初期値が設定される仕組み

# 【課題4】 四則演算を行うクラスの作成

In [107]:
class Arithmetic():
    """
    四則演算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値
        何も入されない、int,float以外が入力された場合は初期値0となる

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value=0):
        if type(value) != int and type(value) != float:
            self.value=0
            print('floatかint型を入れてください')
        else:
            self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def diff(self,value2):
        """
        受け取った引数をself.valueから差し引く
        """
        self.value -= value2
    def multi(self,value2):
        """
        受け取った引数をself.valueへ掛ける
        """
        self.value *= value2
    def div(self,value2):
        """
        受け取った引数をself.valueから割る
        ゼロ除算を避ける
        """
        try:
            self.value /= value2
        except ZeroDivisionError:
            print("ZeroDivisionError!!")

In [132]:
#作ったクラスの__init__が正常確認
arith = Arithmetic(5)
arith = Arithmetic()
arith = Arithmetic('aaa')

初期値5が設定されました
初期値0が設定されました
floatかint型を入れてください
初期値0が設定されました


In [133]:
#クラスのメソッドの確認
arith.add(10)
print(arith.value)
arith.diff(2)
print(arith.value)
arith.multi(2)
print(arith.value)
arith.div(4)
print(arith.value)
arith.div(0)
print(arith.value)

10
8
16
4.0
ZeroDivisionError!!
4.0
